# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\x0c\x66iletransfer\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1f\n\x0c\x46ileResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32U\n\x0c\x46ileTransfer\x12\x45\n\x0c\x44ownloadFile\x12\x19.filetransfer.FileRequest\x1a\x1a.filetransfer.FileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEREQUEST']._serialized_start=28
  _globals['_FILEREQUEST']._serialized_end=59
  _globals['_FILERESPONSE']._serialized_start=61
  _globals['_FILERESPONSE']._serialized_end=92
  _globals['_FILETRANSFER']._serialized_start=94
  _globals['_FILETRANSFER']._serialized_end=179
# @@protoc_insertion_point(module_scope)
